services:
  mongo:
    image: mongo:6
    container_name: recipes-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=recipeadmin
      - MONGO_INITDB_ROOT_PASSWORD=recipepass
      - MONGO_INITDB_DATABASE=recipes_db
    volumes:
      - mongo-data:/data/db
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./backend/app:/app/app
    env_file:
      - ./.env
    environment:
      - MONGO_URI=mongodb://recipeadmin:recipepass@mongo:27017/recipes_db?authSource=admin
      - MONGO_DATABASE=recipes_db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --app-dir /app
    depends_on:
      - mongo
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_PROXY_TARGET=http://backend:8000
    depends_on:
      - backend

  mongo-express:
    image: mongo-express:1.0.2
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=recipeadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=recipepass
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo
    restart: always

volumes:
  mongo-data:
