apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: recipes-app
type: Opaque
stringData:
  MONGO_URI: "mongodb://recipeadmin:recipepass@mongo:27017/recipes_db?authSource=admin"
