kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080
        protocol: TCP
      - containerPort: 443
        hostPort: 8443
        protocol: TCP
      - containerPort: 30573
        hostPort: 30573
        protocol: TCP
      - containerPort: 30800
        hostPort: 30800
        protocol: TCP
      - containerPort: 30881
        hostPort: 30881
        protocol: TCP
